const PHONE_LENGTH_ERROR = '请输入11位数字';
const PASSWORD_NOT_MATCH = '确认密码与密码不一致';
const FORM_BLANK_ERROR = '请完善表格';
const REGISTER_SUCCESS = '注册成功';

export {
	PHONE_LENGTH_ERROR,
	PASSWORD_NOT_MATCH,
	FORM_BLANK_ERROR,
	REGISTER_SUCCESS
};
